CarteiraDigital/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CarteiraDigital.Models
{
    public class Pessoa
    {
        public virtual int Id { get; set; }

        [Required(ErrorMessage = "O campo Nome é obrigatório!")]
        [StringLength(40)]
        [RegularExpression(@"^(?:[A-Za-zÀ-ÿ]{2,} ?)+$", ErrorMessage = "Nome Inválido")]
        public virtual string Nome { get; set; }

        [Required(ErrorMessage = "O campo E-mail é obrigatório!")]
        [StringLength(40)]
        [EmailAddress(ErrorMessage = "O campo E-mail está em formato inválido!")] 
        public virtual string Email { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "O campo Salário deve ser maior ou igual a zero!")]
        public virtual decimal? Salario { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "O campo Limite deve ser maior ou igual a zero!")]
        public virtual decimal? Limite { get; set; }

        [Required(ErrorMessage = "O campo Mínimo é obrigatório!")]
        public virtual decimal? Minimo { get; set; }

        public virtual decimal Saldo { get; set; }

        public virtual IList<MovimentoEntrada> Entradas { get; set; }

        public virtual IList<MovimentoSaida> Saidas { get; set; }

        [Required(ErrorMessage = "O campo Senha é obrigatório!")]
        public virtual string Senha { get; set; }

        [Required(ErrorMessage = "O campo Cargo é obrigatório!")] 
        public virtual int Cargo { get; set; }

        //Construtor:
        public Pessoa()
        {
            Saldo = 0;
        }
    }
} 

CarteiraDigital/Controllers/MovimentosController.cs
using CarteiraDigital.Filters;
using CarteiraDigital.Models;
using CarteiraDigital.Repositorios;
using CarteiraDigital.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CarteiraDigital.Controllers
{
    [PaginaParaUsuarioLogado]
    public class MovimentosController : Controller
    {
        private readonly MovimentosRepository movimentosRepository;
        private readonly PessoaRepository pessoaRepository;

        public MovimentosController(NHibernate.ISession session)
        {
            movimentosRepository = new MovimentosRepository(session);
            pessoaRepository = new PessoaRepository(session);
        }

        [HttpGet]
        public IActionResult GeraMovimentos(int id)
        {
            MovimentoViewModel movimento = new MovimentoViewModel();
            movimento.PessoaId = id;
            return View(movimento);
        }

        public async Task<bool> Deposito(MovimentoViewModel movimento)
        {
            MovimentoEntrada entrada = new MovimentoEntrada();
            entrada.Descricao = movimento.Descricao;
            entrada.Valor = movimento.Valor;
            entrada.PessoaId = await pessoaRepository.FindByID(movimento.PessoaId);

            entrada.PessoaId.Saldo = entrada.PessoaId.Saldo + entrada.Valor;

            await movimentosRepository.Add(entrada);
            await pessoaRepository.Update(entrada.PessoaId);

            return true;
        }

        public async Task<bool> Saque(MovimentoViewModel movimento)
        {
            MovimentoSaida saida = new MovimentoSaida();
            saida.Descricao = movimento.Descricao;
            saida.Valor = movimento.Valor;
            saida.PessoaId = await pessoaRepository.FindByID(movimento.PessoaId);

            if (saida.PessoaId.Limite == null)
            {
                saida.PessoaId.Limite = 0;
            }
            if (movimento.Valor > saida.PessoaId.Saldo + saida.PessoaId.Limite)
            {
                return false;
            }
            else
            {
                saida.PessoaId.Saldo = saida.PessoaId.Saldo - movimento.Valor;
                await movimentosRepository.Add(saida);
                await pessoaRepository.Update(saida.PessoaId);
                return true;
            }
        }

        [HttpPost]
        public async Task<IActionResult> GeraMovimentos(MovimentoViewModel movimento)
        {
            if (movimento.Tipo == "1" && await Deposito(movimento))
            {
                ViewBag.Script = "<script>Swal.fire({icon: 'success', title: 'Sucesso', text: 'Depósito Realizado com Sucesso!', position: 'bottom-center', timer: 2000, showConfirmButton: false});</script>";
                return View(movimento);
            }
            else
            {
                MovimentoSaida saida = new MovimentoSaida();
                saida.Descricao = movimento.Descricao;
                saida.Valor = movimento.Valor;
                saida.PessoaId = await pessoaRepository.FindByID(movimento.PessoaId);

                if (await Saque(movimento))
                {
                    if (saida.PessoaId.Minimo < saida.PessoaId.Saldo)
                    {
                        ViewBag.Script = "<script>Swal.fire({icon: 'success', title: 'Sucesso', text: 'Saque Realizado com Sucesso!', position: 'bottom-center', timer: 2000, showConfirmButton: false});</script>"; 
                        return View(movimento);
                    }
                }

                if (!await Saque(movimento))
                {
                    ViewBag.Script = "<script>Swal.fire({icon: 'error', title: 'Atenção', text: 'Você não possui saldo e nem limite suficientes para realizar o saque', position: 'bottom-center', timer: 2500, showConfirmButton: false});</script>";
                    return View(movimento);
                }

                ViewBag.Script = "<script>Swal.fire({icon: 'warning', title: 'Atenção', text: 'Saque Realizado com Sucesso. Contudo, seu Saldo ficou abaixo do Mínimo!', position: 'bottom-center', timer: 2500, showConfirmButton: false});</script>";
                return View(movimento);
            }
        }

        public async Task<ActionResult> ExtratoAsync(int id)
        {
            IList<MovimentoViewModel> movimentos = movimentosRepository.FindAll(id);
            ViewBag.mov = movimentos;
            ViewBag.id = id;
            Pessoa p = await pessoaRepository.FindByID(id);
            ViewBag.Nome = p.Nome;
            ViewBag.Saldo = p.Saldo;
            ViewBag.SaldoAnterior = 0.0;
            return View();
        }

        public ActionResult FiltroExtrato(Filtro filtro, int id)
        {
            List<MovimentoViewModel> movimentos = movimentosRepository.FindAll(id);
            IList<MovimentoViewModel> movimentosFiltrados = new List<MovimentoViewModel>();
            ViewBag.id = id;

            DateTime ultimos7dias = DateTime.Now.AddDays(-7);
            DateTime ultimos15dias = DateTime.Now.AddDays(-15);
            DateTime ultimos30dias = DateTime.Now.AddDays(-30);
            DateTime? dataInicio = null;
            DateTime? dataFim = null;

            switch (filtro.tipoPeriodo)
            {
                case 0:
                    dataInicio = ultimos7dias.Date;
                    dataFim = DateTime.Now.Date;
                    break;
                case 1:
                    dataInicio = ultimos15dias.Date;
                    dataFim = DateTime.Now.Date;
                    break;
                case 2:
                    dataInicio = ultimos30dias.Date;
                    dataFim = DateTime.Now.Date;
                    break;
                case 3:
                    dataInicio = filtro.dataInicio;
                    dataFim = filtro.dataFim;
                    break;
            }

            decimal valorTotalEntradas = 0;
            decimal valorTotalSaidas = 0;

            foreach (var item in movimentos)
            {
                if ((filtro.tipoMovimento == 0 && item.Tipo == "Entrada") ||
                    (filtro.tipoMovimento == 1 && item.Tipo == "Saída") ||
                    (filtro.tipoMovimento == 2))
                {
                    if (item.Data.Date >= dataInicio && item.Data.Date <= dataFim)
                    {
                        movimentosFiltrados.Add(item);

                        if (item.Tipo == "Entrada")
                        {
                            valorTotalEntradas = valorTotalEntradas + item.Valor;
                        }
                        else if (item.Tipo == "Saída")
                        {
                            valorTotalSaidas = valorTotalSaidas + item.Valor;
                        }
                    }
                }
            }

            decimal saldoAtual = 0;

            if (filtro.tipoMovimento == 0)
            {
                saldoAtual = valorTotalEntradas;
            }
            else if (filtro.tipoMovimento == 1)
            {
                saldoAtual = -valorTotalSaidas;
            }
            else
            {
                decimal valorTotalanteriorFiltrado = 0;

                foreach (var mov in movimentos)
                {
                    if (mov.Data < dataInicio)
                    {
                        decimal valorMovimento = mov.Tipo == "Entrada" ? mov.Valor : -mov.Valor;
                        valorTotalanteriorFiltrado = valorTotalanteriorFiltrado + valorMovimento;
                    }
                }

                saldoAtual = valorTotalEntradas - valorTotalSaidas + valorTotalanteriorFiltrado;
                ViewBag.SaldoAnterior = valorTotalanteriorFiltrado;
            }

            ViewBag.Saldo = saldoAtual;
            ViewBag.mov = movimentosFiltrados;

            if (filtro.tipoMovimento == 0 || filtro.tipoMovimento == 1)
            {
                ViewBag.SaldoAnterior = 0.0;
                ViewBag.MostrarViewBag = false;
            }
            else
            {
                ViewBag.MostrarViewBag = true;
            }

            return View("Extrato");
        }
    }
} 

CarteiraDigital/Controllers/PessoaController.cs
using CarteiraDigital.Filters;
using CarteiraDigital.Helper;
using CarteiraDigital.Models;
using CarteiraDigital.Repositorios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarteiraDigital.Controllers
{
    //[PaginaRestritaSomenteAdmin]
    public class PessoaController : Controller
    {
        private readonly PessoaRepository pessoaRepository;

        public PessoaController(NHibernate.ISession session)
        {
            pessoaRepository = new PessoaRepository(session);
        }

        //Tela só de Adm: 
        [HttpGet]
        public ActionResult Index()
        {
            IList<Pessoa> Pessoas = pessoaRepository.FindByID().ToList();
            return View(Pessoas.Reverse<Pessoa>());
        }
        
        //Tela só de Cliente: 
        //[HttpGet]
        //public ActionResult Cliente(Pessoa pessoa)
        //{

        //    Pessoa pessoa = pessoaRepository.FindByEmail(pessoa.Email);


        //    return View(pessoa);  
        //}

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(Pessoa pessoa)
        {
            var pessoaExistente = pessoaRepository.FindByEmail(pessoa.Email);

            if (pessoaExistente == null)
            {
                if (ModelState.IsValid)
                {
                    await pessoaRepository.Add(pessoa);
                    ViewBag.Script = @"
                    <script>
                    Swal.fire({
                    icon: 'success',
                    title: 'Sucesso',
                    text: 'Cadastro Realizado com Sucesso!',
                    position: 'bottom-center',
                    timer: 2000,
                    showConfirmButton: false
                    });

                    setTimeout(function () {
                    const inputs = document.querySelectorAll('input[data-span-id]');
                    inputs.forEach(function (input) {
                        input.value = '';
                    });

                    const spans = document.querySelectorAll('[data-span-id]');
                    spans.forEach(function (span) {
                        span.textContent = '';
                    });
                    }, 1000);

                    document.addEventListener('DOMContentLoaded', function () {
                    const inputs = document.querySelectorAll('input[data-span-id]');
                    inputs.forEach(function (input) {
                        input.addEventListener('click', function () {
                            const spanId = input.getAttribute('data-span-id');
                            const span = document.getElementById(spanId);
                            if (span) {
                                span.textContent = '';
                            }
                        });

                        input.addEventListener('focus', function () {
                            const spanId = input.getAttribute('data-span-id');
                            const span = document.getElementById(spanId);
                            if (span) {
                                span.textContent = '';
                            }
                        });
                    });
                    }); 
                    </script>";
                }

                return View(pessoa);
            }
            else
            {
                ViewBag.Script = @"
                    <script>
                    Swal.fire({
                    icon: 'warning',
                    title: 'Atenção',
                    text: 'O E-mail Informado já está em uso! Insira outro para continuar!',
                    position: 'bottom-center',
                    timer: 2000,
                    showConfirmButton: false
                    });
                </script>";

                return View(pessoa);
            }
        }

        public async Task<IActionResult> Deletar(int id)
        {
            await pessoaRepository.Remove(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Atualizar(int id)
        {
            Pessoa pessoa = await pessoaRepository.FindByID(id);
            return View(pessoa);
        }

        [HttpPost]
        public async Task<IActionResult> Atualizar(Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                await pessoaRepository.Update(pessoa);
                ViewBag.Script = " < script>Swal.fire({icon: 'success', title: 'Sucesso', text: 'Dados Atualizados com Sucesso!', position: 'bottom-center', timer: 2000, showConfirmButton: false});</script>";
            }

            return View(pessoa);
        }

        public async Task<IActionResult> Detalhes(int id)
        {
            Pessoa pessoa = await pessoaRepository.FindByID(id);
            return View(pessoa);
        }
    }
} 

CarteiraDigital/Views/Pessoa/Atualizar.cshtml
@model CarteiraDigital.Models.Pessoa

@{
    ViewData["Title"] = "Atualizar";
}

<h1>Atualizar</h1> 
<h4>Pessoa</h4> 
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Atualizar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control"/>
            <input type="hidden" asp-for="Saldo" class="form-control"/>
            <div class="card">
                <div class="card-header">Dados Pessoais</div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Nome" class="control-label">Nome</label>
                        <input asp-for="Nome" class="form-control"readonly/>
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label">Email</label>
                        <input asp-for="Email" class="form-control" id="email"/> 
                        <span asp-validation-for="Email" class="text-danger" id="erro-email"></span>  
                    </div>
                </div>
            </div>
            <div class="card  mt-3">
                <div class="card-header">Dados Bancários</div>
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Salario" class="control-label">Salário</label>
                        <input type="number" asp-for="Salario" class="form-control" oninput="limitarTamanho(this, 30)"/>
                        <span asp-validation-for="Salario" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Limite" class="control-label">Limite</label>
                        <input type="number" asp-for="Limite" class="form-control" oninput="limitarTamanho(this, 30)"/>
                        <span asp-validation-for="Limite" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Minimo" class="control-label">Mínimo</label>
                        <input type="number" asp-for="Minimo" class="form-control" id="minimo" oninput="limitarTamanho(this, 30)"/>
                        <span asp-validation-for="Minimo" class="text-danger" id="erro-minimo"></span>
                    </div> 
                </div>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Atualizar" class="btn btn-dark"/>
                @Html.Raw(ViewBag.Script)
                <a asp-action="Index" class="btn btn-light ml-3">Voltar</a> 
            </div>
        </form>
    </div>
</div> 

<script>
    document.getElementById('email').addEventListener('input', limparAlertaEmail);
    document.getElementById('minimo').addEventListener('input', limparAlertaMinimo);

    function limitarTamanho(elemento, tamanhoMaximo) {
        if (elemento.value.length > tamanhoMaximo) {
            elemento.value = elemento.value.slice(0, tamanhoMaximo);
        }
    }
    function limparAlertaEmail() {
        var erroEmail = document.getElementById('erro-email');
        erroEmail.textContent = '';
    }
    function limparAlertaMinimo() {
        var erroMinimo = document.getElementById('erro-minimo');
        erroMinimo.textContent = '';
    }
</script> 

CarteiraDigital/Views/Pessoa/Cadastrar.cshtml
@model CarteiraDigital.Models.Pessoa

@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastrar</h1>
<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Cadastrar" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome</label>
                <input asp-for="Nome" class="form-control" data-span-id="span-nome" id="nome" placeholder="Ex: Aquiles Moroni" />
                <span asp-validation-for="Nome" class="text-danger" id="erro-nome"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">E-mail</label>
                <input asp-for="Email" class="form-control" data-span-id="span-email" id="email" placeholder="Ex: aquilesmoroni@hotmail.com" />
                <span asp-validation-for="Email" class="text-danger" id="erro-email"></span>
            </div>
            <div class="form-group">
                <label asp-for="Minimo" class="control-label">Mínimo</label>
                <input asp-for="Minimo" type="number" class="form-control" data-span-id="span-minimo" id="minimo" placeholder="Ex: 50,00" oninput="limitarTamanho(this, 30)" />
                <span asp-validation-for="Minimo" class="text-danger" id="erro-minimo"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label">Senha</label>
                <input asp-for="Senha" type="password" class="form-control" data-span-id="span-senha" id="senha" placeholder="Ex: #$jY5489_" oninput="limitarTamanho(this, 30)" />
                <span asp-validation-for="Senha" class="text-danger" id="erro-senha"></span>
            </div>
            <div class="form-group form-check p-0 mt-3 mb-0">
                <div class="form-check form-check-inline">
                    <input asp-for="Cargo" class="form-check-input" value="1" type="radio" id="administrador">
                    <label asp-for="Cargo" class="form-check-label" for="inlineRadio1">Administrador</label> 
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="Cargo" class="form-check-input" value="2" type="radio" id="cliente">
                    <label asp-for="Cargo" class="form-check-label" for="inlineRadio2">Cliente</label>
                </div>
            </div>
            <span asp-validation-for="Cargo" class="text-danger" id="erro-cargo"></span>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-dark mt-3" id="btn_criaCargo"/>
                @Html.Raw(ViewBag.Script)
                <a asp-action="Index" class="btn btn-light mt-3 ml-3">Voltar</a>
            </div>
        </form>
    </div>
</div> 

<script>
    document.getElementById('nome').addEventListener('input', limparAlertaNome);
    document.getElementById('email').addEventListener('input', limparAlertaEmail);
    document.getElementById('minimo').addEventListener('input', limparAlertaMinimo);
    document.getElementById('senha').addEventListener('input', limparAlertaSenha);
    document.getElementById('administrador').checked = false;
    document.getElementById('cliente').checked = false;
    document.getElementById('administrador').addEventListener('input', LimparAlertaCargo);
    document.getElementById('cliente').addEventListener('input', LimparAlertaCargo);

    function limitarTamanho(elemento, tamanhoMaximo) {
        if (elemento.value.length > tamanhoMaximo) {
            elemento.value = elemento.value.slice(0, tamanhoMaximo);
        }
    } 
    function limparAlertaNome() {
        var erroNome = document.getElementById('erro-nome');
        erroNome.textContent = '';
    }
    function limparAlertaEmail() {
        var erroEmail = document.getElementById('erro-email');
        erroEmail.textContent = '';
    }
    function limparAlertaMinimo() {
        var erroMinimo = document.getElementById('erro-minimo');
        erroMinimo.textContent = '';
    }
    function limparAlertaSenha() {
        var erroSenha = document.getElementById('erro-senha');
        erroSenha.textContent = '';
    } 
</script>

CarteiraDigital/Views/Pessoa/Cliente.cshtml
@model IEnumerable<CarteiraDigital.Models.Pessoa>
@using Newtonsoft.Json;

@{
    ViewData["Title"] = "Cliente";
}

<h3 class="mb-4">Configurações da Conta</h3>

<p>
    <a asp-controller="Home" asp-action="Index" class="btn btn-light mt-2 ml-4 mb-4">Voltar</a>
</p>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cargo)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="pt-3">
                        @Html.DisplayFor(modelItem => item.Nome)
                        @if (item.Saldo < item.Minimo)
                        {
                            <p class="text-danger mb-0">Saldo Abaixo do Mínimo!</p>
                        }
                    </td>
                    <td class="pt-3">
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td class="pt-3">
                        @if (item.Cargo == 1)
                        {
                            <text>Administrador</text>
                        }
                        else if (item.Cargo == 2)
                        {
                            <text>Cliente</text>
                        }
                    </td>
                    <td class="pl-4 pr=0 d-flex justify-content-between">
                        <button class="btn btn-danger" data-toggle="modal" data-target="#Delete-@item.Id">Excluir</button>
                        <div class="modal fade" id="Delete-@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">Excluir</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Tem Certeza que Deseja Excluir @item.Nome?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <a asp-controller="Pessoa" asp-action="Deletar" asp-route-id="@item.Id" class="btn btn-danger">Excluir</a>
                                        @Html.Raw(ViewBag.Script)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a asp-controller="Pessoa" asp-action="Atualizar" class="btn btn-success" asp-route-id="@item.Id">Atualizar</a>
                        <a asp-controller="Pessoa" asp-action="Detalhes" class="btn btn-primary" asp-route-id="@item.Id">Detalhes</a>
                        <a asp-controller="Movimentos" asp-action="GeraMovimentos" class="btn btn-warning" asp-route-id="@item.Id">Movimentos</a>
                        <a asp-controller="Movimentos" asp-action="Extrato" asp-route-id="@item.Id" class="btn btn-dark">Extrato</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CarteiraDigital/Views/Pessoa/Index.cshtml
@model IEnumerable<CarteiraDigital.Models.Pessoa>
@using Newtonsoft.Json;

@{
    ViewData["Title"] = "Index";
}

<h1 class="mb-4">Início</h1>

<p>
    <a asp-action="Cadastrar" class="btn btn-dark mt-2 mb-4">Cadastrar</a>
    <a asp-controller="Home" asp-action="Index" class="btn btn-light mt-2 ml-4 mb-4">Voltar</a>
</p>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cargo)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
             {
              <tr>
                <td class="pt-3">
                    @Html.DisplayFor(modelItem => item.Nome)
                    @if (item.Saldo < item.Minimo)
                    {
                        <p class="text-danger mb-0">Saldo Abaixo do Mínimo!</p>
                    }
                </td>
                <td class="pt-3">
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td class="pt-3">
                    @if (item.Cargo == 1)
                    {
                        <text>Administrador</text>
                    }
                    else if (item.Cargo == 2)
                    {
                        <text>Cliente</text>
                    } 
                </td> 
                <td class="pl-4 pr=0 d-flex justify-content-between">
                    <button class="btn btn-danger" data-toggle="modal" data-target="#Delete-@item.Id">Excluir</button>
                    <div class="modal fade" id="Delete-@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Excluir</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Tem Certeza que Deseja Excluir @item.Nome?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <a asp-controller="Pessoa" asp-action="Deletar" asp-route-id="@item.Id" class="btn btn-danger">Excluir</a>
                                    @Html.Raw(ViewBag.Script)
                                </div>
                            </div>
                        </div>
                    </div>
                    <a asp-controller="Pessoa" asp-action="Atualizar" class="btn btn-success" asp-route-id="@item.Id">Atualizar</a>
                    <a asp-controller="Pessoa" asp-action="Detalhes" class="btn btn-primary" asp-route-id="@item.Id">Detalhes</a>
                    <a asp-controller="Movimentos" asp-action="GeraMovimentos" class="btn btn-warning" asp-route-id="@item.Id">Movimentos</a>
                    <a asp-controller="Movimentos" asp-action="Extrato" asp-route-id="@item.Id" class="btn btn-dark">Extrato</a>
                </td>
              </tr>
             } 
        </tbody>
    </table>
</div>